string[] skill_names
bool localize_box
string template_name
float32 speed_factor
---
bool success
---
string skill_name
int32 waypoint_index
bool spiraling
bool camera_feedback
bool stiffness
bool gripper
